name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment8-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          
          # ADD CACHE FOR buildroot/dl (downloaded sources)
          - name: Cache buildroot downloads (dl/)
            uses: actions/cache@v4
            with:
              path: buildroot/dl
              key: buildroot-dl-${{ hashFiles('buildroot/package/**', 'buildroot/Config.in') }}
              restore-keys: |
                buildroot-dl-

          # (Optional) ADD CACHE FOR buildroot/output/build (built package trees)
          - name: Cache buildroot output/build (optional)
            uses: actions/cache@v4
            with:
              path: buildroot/output/build
              key: buildroot-build-${{ hashFiles('buildroot/**') }}
              restore-keys: |
                buildroot-build-

          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
